include: package:flutter_lints/flutter.yaml

linter:
  rules:
    public_member_api_docs: false

analyzer:
  errors:
    no_default_cases: ignore
    sort_pub_dependencies: ignore
  exclude:
    - "**/*_generated.dart"
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.gen.dart"
