name: openquester
description: "A new Flutter project."
publish_to: "none"
version: 0.13.2

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: 3.29.3

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  auto_route: ^10.0.1
  openapi:
    path: ../openapi/dart_sdk/
  envied: ^1.1.1
  package_info_plus: ^8.3.0
  logger: ^2.5.0
  flutter_native_splash: ^2.4.6
  dio: ^5.8.0+1
  file_picker: ^10.1.2
  siq_file:
    path: ./packages/siq_file/
  siq_compress:
    path: ./packages/siq_compress/
  injectable: ^2.5.0
  get_it: ^8.0.3
  watch_it: ^1.6.5
  shared_preferences: ^2.5.3
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  universal_io: ^2.2.2
  socket_io_client: ^3.1.1
  easy_localization: ^3.0.7+1
  infinite_scroll_pagination: ^5.0.0
  nb_utils: ^7.1.2
  dio_cache_interceptor: ^4.0.3
  oauth2_client: ^4.1.0
  dio_cookie_manager: ^3.2.0
  path_provider: ^2.1.5
  cookie_jar: ^4.0.8
  flutter_web_auth_2: ^5.0.0-alpha.2
  universal_web: ^1.1.0+2
  cross_file: ^0.3.4+2
  squadron: ^7.1.1
  collection: ^1.19.1
  flutter_chat_core: ^0.0.11
  flutter_chat_ui: ^2.0.0-dev.10
  cached_network_image: ^3.4.1
  cached_network_image_platform_interface: ^4.1.1
  fetch_client: ^1.1.4
  crypto: ^3.0.6
  flutter_svg: ^2.1.0
  mocktail: ^1.0.4
  updat: ^1.3.2
  throttling: ^2.0.1
  file_saver: ^0.2.14
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  analyzer: ^7.4.4
  auto_route_generator: ^10.0.1
  flutter_launcher_icons: ^0.14.3
  envied_generator: ^1.1.1
  injectable_generator: ^2.7.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  test: ^1.25.15
  flutter_gen_runner: ^5.10.0
  very_good_analysis: ^7.0.0
  squadron_builder: ^7.1.1
  inno_bundle: ^0.9.0

dependency_overrides:
  archive: ^4.0.7 # Force for updat

flutter:
  uses-material-design: true
  assets:
    - assets/localization/
    - assets/icons/

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true

msix_config:
  display_name: OpenQuester
  identity_name: com.asion.openquester
  logo_path: assets/icon/icon.png
  capabilities: internetClient
  languages: en-us
  file_extension: .siq
  install_certificate: false

inno_bundle:
  id: 2c5b1f10-2d9d-11f0-947a-894be89259d5
  name: OpenQuester
  publisher: OpenQuester
  installer_icon: assets/icon/icon.ico
  url: https://openquester.app/
  updates_url: https://github.com/OpenQuester/OpenQuester/releases
  admin: false
  languages:
    - english
