name: openquester
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: 3.24.3

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^9.2.2
  openapi:
    path: ../openapi/dart_sdk/
  envied: ^0.5.4+1
  package_info_plus: ^8.1.0
  logger: ^2.4.0
  flutter_native_splash: ^2.4.2
  dio: ^5.7.0
  file_picker: ^8.1.3
  siq_file:
    path: ./packages/siq_file/
  injectable: ^2.5.0
  get_it: ^8.0.1
  watch_it: ^1.5.1
  shared_preferences: ^2.3.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  universal_io: ^2.2.2
  socket_io_client: ^3.0.0
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  analyzer: ^6.7.0
  auto_route_generator: ^9.0.0
  flutter_launcher_icons: ^0.14.1
  envied_generator: ^0.5.4+1
  injectable_generator: ^2.6.2
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  test: ^1.25.7
  flutter_gen_runner: ^5.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/localization/

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
