# Development database setup

services:
  postgres:
    image: postgres:16.3-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Creds to the server above:
  # Host name/adress: postgres (localhost for local services)
  # Username: postgres
  # Password: mysecretpassword
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin:
