# Development database setup

services:
  postgres:
    image: postgres:16.3-alpine
    container_name: postgres
    env_file: ./.env.pg
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Url: http://localhost:5050/
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file: ./.env.pg.admin
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin:
