# * Docker compose setup for development

services:
  postgres:
    image: postgres:16.3-alpine
    container_name: postgres
    env_file: ./.env.pg
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Url: http://localhost:5050/
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file: ./.env.pg.admin
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin

  # Url: http://localhost:9000/ and console on http://localhost:9001/
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"

volumes:
  pgdata:
  pgadmin:
