name: siq_file
description: A sigame file parser
version: 0.0.1
# repository: https://github.com/my_org/my_repo
topics: [cli]

environment:
  sdk: ">=3.7.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  cli_completion: ^0.5.1
  mason_logger: ^0.3.2
  universal_io: ^2.2.2
  path: ^1.9.1
  archive: ^4.0.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  xml: ^6.5.0
  collection: ^1.19.1
  logger: ^2.5.0
  crypto: ^3.0.6
  convert: ^3.1.2

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  build_runner: ^2.4.15
  build_version: ^2.1.1
  freezed: ^2.5.8
  json_serializable: ^6.9.4

executables:
  siq_file:
