analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
    strict-casts: false
  exclude:
    - test/*.dart
    - lib/src/api/default_api.dart
  errors:
    deprecated_member_use_from_same_package: ignore
