name: openapi
version: 1.0.0
description: OpenAPI API client
homepage: homepage

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  dart_mappable: ^4.3.0 # for dart_mappable
  dio: ^5.7.0
  freezed_annotation: ^2.4.4 # for freezed
  json_annotation: ^4.9.0
  retrofit: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.14
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.7
  dart_mappable_builder: ^4.3.0 # for dart_mappable
  swagger_parser:
    git:
      url: https://github.com/Asion001/swagger_parser.git
      path: swagger_parser
