name: openapi
version: 1.0.0
description: OpenAPI API client
homepage: homepage

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  dart_mappable: ^4.2.2 # for dart_mappable
  dio: ^5.7.0
  freezed_annotation: ^2.4.4 # for freezed
  json_annotation: ^4.9.0
  retrofit: ^4.4.1

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.5
  dart_mappable_builder: ^4.2.3 # for dart_mappable
  swagger_parser: ^1.19.2
