export const GAME_NAMESPACE = "game";
export const GAME_ID_CHARACTERS_LENGTH = 4;
export const GAME_ID_CHARACTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
export const GAME_TITLE_MAX_CHARS = 70;
export const GAME_TITLE_MIN_CHARS = 3;
export const GAME_MAX_PLAYERS = 15;
export const GAME_ROOM_NAMESPACE = `${GAME_NAMESPACE}:room`;
