name: Build Client

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build client app
    # Skip when PR from a fork
    if: ${{ !github.event.pull_request.head.repo.fork && github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: ./client/pubspec.yaml
          cache: true
      - run: flutter pub get
      - run: dart run build_runner build --delete-conflicting-outputs
      - name: Build web
        run: flutter build web --wasm --no-web-resources-cdn

      - name: Build android
        run: |
          flutter build apk --release
          flutter build apk --release --split-per-abi --target-platform android-arm,android-arm64,android-x64
      - name: Publish Web Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-app
          path: ./build/web/
      - name: Publish Android Artifacts
        uses: actions/upload-artifact@v4
        if: github.event_name == 'workflow_call'
        with:
          name: android-app
          path: ./build/app/outputs/flutter-apk/*.apk
