name: Build Client

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and sign Android
    # Skip when PR from a fork
    if: ${{ !github.event.pull_request.head.repo.fork && github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    env:
      working-directory: ./client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: ${{ env.working-directory }}/pubspec.yaml
          cache: true

      - name: Get Packages
        working-directory: ${{ env.working-directory }}
        run: flutter pub get

      - name: Build
        working-directory: ${{ env.working-directory }}
        run: |
          flutter build web --wasm --no-web-resources-cdn
          flutter build apk --release
          flutter build apk --release --split-per-abi --target-platform android-arm,android-arm64,android-x64

      - name: Publish Web Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-app
          path: ${{ env.working-directory }}/build/web/

      - name: Publish Android Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: ${{ env.working-directory }}/build/app/outputs/flutter-apk/*.apk
