name: Build Client

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
    secrets:
      ANDROID_KEYSTORE_PASSWORD:
        required: true
      ANDROID_KEY_PASSWORD:
        required: true
      ANDROID_KEYSTORE_BASE64:
        required: true

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.found_paths.outputs.client == 'true' || steps.should_force.outputs.should_force == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: found_paths
        uses: dorny/paths-filter@v3
        with:
          filters: |
            client:
              - 'client/**'
      - name: Check if we should force jobs to run
        id: should_force
        run: echo "should_force=${{ github.event_name == 'workflow_dispatch' || github.workflow == 'Release' }}" >> "$GITHUB_OUTPUT"

  build:
    name: Build client app
    needs: pre_job
    # Skip when PR from a fork
    if: ${{ !github.event.pull_request.head.repo.fork && github.actor != 'dependabot[bot]' && needs.pre_job.outputs.should_run == 'true'}}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    env:
      DONT_USE_PURO: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: ./client/pubspec.yaml
          cache: true
      - run: flutter pub get
      - name: Write env file
        run: echo "${{ vars.ENV_FILE_CONTENT }}" > .env
      - run: make pre_run
      - name: Build web
        run: flutter build web --no-web-resources-cdn --build-number $GITHUB_RUN_NUMBER
      - name: Publish Web Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-app
          path: ./client/build/web/
      - name: Decode and setup keystore
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/app/upload-keystore.jks
      - name: Build android
        env:
          ANDROID_KEYSTORE_PATH: ${{ vars.ANDROID_KEYSTORE_PATH }}
          ANDROID_KEY_ALIAS_NAME: ${{ vars.ANDROID_KEY_ALIAS_NAME }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          flutter build apk --release --build-number $GITHUB_RUN_NUMBER
          flutter build apk --release --split-per-abi --target-platform android-arm,android-arm64,android-x64 --build-number $GITHUB_RUN_NUMBER
      - name: Publish Android Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: ./client/build/app/outputs/flutter-apk/*.apk
