name: Build server

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    types: [review_requested, ready_for_review]

jobs:
  pre-job:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.found_paths.outputs.server == 'true' || steps.should_force.outputs.should_force == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: found_paths
        uses: dorny/paths-filter@v3
        with:
          filters: |
            server:
              - 'server/**'
      - name: Check if we should force jobs to run
        id: should_force
        run: echo "should_force=${{ github.event_name == 'workflow_call' || github.event_name == 'workflow_dispatch' }}" >> "$GITHUB_OUTPUT"

  build_server:
    runs-on: ubuntu-latest
    needs: pre-job
    # Skip when PR from a fork
    if: ${{ !github.event.pull_request.head.repo.fork && github.actor != 'dependabot[bot]' && needs.pre-job.outputs.should_run == 'true' }}
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
      - name: Use the latest stable Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "./server/.node-version"
          cache: "npm"
          cache-dependency-path: ./server/package-lock.json
      - name: Install Dependencies
        run: npm ci
      - name: Run Build
        run: npm run build
