name: Check Changes

on:
  workflow_call:
    outputs:
      client_changes:
        value: ${{ jobs.check-changes.outputs.client_changes }}
      server_changes:
        value: ${{ jobs.check-changes.outputs.server_changes }}

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      client_changes: ${{ steps.check.outputs.client_changes }}
      server_changes: ${{ steps.check.outputs.server_changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: git fetch --depth=2

      - name: Check for changes in folders
        id: check
        run: |
          # Get the latest commit hashes
          latest_commit=$(git rev-parse HEAD)
          previous_commit=$(git rev-parse HEAD~1)

          # Initialize flags for changes
          client_changes=false
          server_changes=false

          folders=["server","client"]

          # Loop through the provided folders
          for folder in $folders; do
            if git diff --quiet $previous_commit $latest_commit -- "$folder"; then
              echo "No changes in $folder"
            else
              echo "Changes detected in $folder"
              if [[ "$folder" == *"client"* ]]; then
                client_changes=true
              elif [[ "$folder" == *"server"* ]]; then
                server_changes=true
              fi
            fi
          done

          # Set environment variables
          echo "client_changes=$client_changes" >> $GITHUB_ENV
          echo "server_changes=$server_changes" >> $GITHUB_ENV
