name: Check Changes

on:
  workflow_call:
    outputs:
      client_changes:
        value: ${{ jobs.check-changes.outputs.client_changes }}
      server_changes:
        value: ${{ jobs.check-changes.outputs.server_changes }}

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      client_changes: ${{ steps.client_check.outputs.client_changes }}
      server_changes: ${{ steps.server_check.outputs.server_changes }}
    steps:
      - uses: actions/checkout@v4

      - id: server-changed-files
        name: Check server files
        uses: knu/changed-files@v1
        with:
          paths: |
            server/**

      - name: Server changes
        id: server_check
        if: steps.server-changed-files.outputs.matched_files != ''
        run: echo "server_changes=true" >> $GITHUB_OUTPUT

      - id: client-changed-files
        name: Check client files
        uses: knu/changed-files@v1
        with:
          paths: |
            client/**

      - name: Client changes
        id: client_check
        if: steps.client-changed-files.outputs.matched_files != ''
        run: echo "client_changes=true" >> $GITHUB_OUTPUT
