name: Check Changes

on:
  workflow_call:
    outputs:
      client_changes:
        value: ${{ jobs.check-changes.outputs.client_changes }}
      server_changes:
        value: ${{ jobs.check-changes.outputs.server_changes }}

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      client_changes: ${{ steps.check.outputs.client_changes }}
      server_changes: ${{ steps.check.outputs.server_changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            server:
              - 'server/'
            client:
              - 'client/'

      - name: Client changes
        if: steps.filter.outputs.server == 'true'
        run: echo "client_changes=true" >> $GITHUB_ENV

      # run only if not 'workflows' files were changed
      - name: Server changes
        if: steps.filter.outputs.client != 'true'
        run: echo "server_changes=true" >> $GITHUB_ENV
