name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/test.yml

  build_client:
    needs: [tests]
    uses: ./.github/workflows/build_client.yml

  build_docker:
    needs: [tests]
    uses: ./.github/workflows/docker.yml
    permissions:
      contents: read
      packages: write

  publish_release:
    runs-on: ubuntu-latest
    needs: [build_client, build_docker, tests]
    permissions:
      contents: write
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download WEB
        uses: actions/download-artifact@v4
        with:
          name: web-app
          path: web/

      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: android-app

      - name: Set latest tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0 | tail -n1)
          echo "LATEST_TAG=$LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          tag_name: ${{ env.LATEST_TAG }}
          #TODO: body_path: misc/release/notes.tmpl
          files: |
            *.apk

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: openquester
          directory: web/
          branch: main
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Purge Cloudflare cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
