name: Test

on:
  workflow_dispatch:
  workflow_call:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_run_server: ${{ steps.found_paths.outputs.server == 'true' || steps.should_force.outputs.should_force == 'true' }}
      should_run_client: ${{ steps.found_paths.outputs.client == 'true' || steps.should_force.outputs.should_force == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: found_paths
        uses: dorny/paths-filter@v3
        with:
          filters: |
            server:
              - 'server/**'
            client:
              - 'client/**'
      - name: Check if we should force jobs to run
        id: should_force
        run: echo "should_force=${{ github.event_name == 'workflow_dispatch' }}" >> "$GITHUB_OUTPUT"

  test_server:
    runs-on: ubuntu-latest
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_run_server == 'true' }}
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
      - name: Use the latest stable Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./server/.node-version
          cache: "npm"
          cache-dependency-path: ./server/package-lock.json
      - name: Install Dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run Test
        run: npm run test

  test_client:
    runs-on: ubuntu-latest
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_run_client == 'true' }}
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: ./client/pubspec.yaml
          cache: true
      - name: Get packages
        run: flutter pub get
      - name: Run dart analyze
        run: dart analyze --fatal-infos
      - name: Run dart format
        run: dart format lib --set-exit-if-changed
      - name: Run dart test
        run: dart test
