name: Test

on:
  workflow_dispatch:
  workflow_call:
  pull_request:

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_run_server: ${{ steps.found_paths.outputs.server == 'true' || steps.should_force.outputs.should_force == 'true' }}
      should_run_client: ${{ steps.found_paths.outputs.client == 'true' || steps.should_force.outputs.should_force == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: found_paths
        uses: dorny/paths-filter@v3
        with:
          filters: |
            server:
              - 'server/**'
            client:
              - 'client/**'
      - name: Check if we should force jobs to run
        id: should_force
        run: echo "should_force=${{ github.event_name == 'workflow_dispatch' ||  github.event_name == 'workflow_call'}}" >> "$GITHUB_OUTPUT"

  test_server:
    runs-on: ubuntu-latest
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_run_server == 'true' }}
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
      - name: Use the latest stable Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./server/.node-version
          cache: "npm"
          cache-dependency-path: ./server/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run test

  test_client:
    runs-on: ubuntu-latest
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_run_client == 'true' }}
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: ./client/pubspec.yaml
          cache: true
      - run: flutter pub get
      - run: dart run build_runner build --delete-conflicting-outputs
      # Ignore editing of api_config file
      # fixes dart format error
      - run: git restore lib/src/connection/api/api_config.dart
      - run: dart analyze --fatal-infos
      - run: dart format lib --set-exit-if-changed
      - run: dart test
